services:
  rabbitmq:
    image: rabbitmq:4.0.9-management-alpine
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data

  pushgateway:
    image: prom/pushgateway:v1.11.1
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:v3.4.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  rabbitmq_data:
