services:
  rabbitmq:
    image: rabbitmq:4.0.9-management-alpine
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data

volumes:
  rabbitmq_data:
